# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxPerm <- function(A) {
    .Call(`_BosonSampling_cxPerm`, A)
}

cxPermMinors <- function(C) {
    .Call(`_BosonSampling_cxPermMinors`, C)
}

rePerm <- function(B) {
    .Call(`_BosonSampling_rePerm`, B)
}

